### ISSUE TITLE
[14.0]attribute_set

### ISSUE THREAD

**Issue by flotho** [OCA/odoo-pim#143]
## Module
attribute_set

## Describe the bug
impossible to install the module
here are the logs :
```
Odoo Server 14.0:test_odoo_preprod_14:ERROR:odoo.sql_db:bad query: SELECT company_dependent FROM attribute_attribute WHERE field_id=17261
                                         ERROR: ERREUR:  la relation « attribute_attribute » n'existe pas
                                         LIGNE 1 : SELECT company_dependent FROM attribute_attribute WHERE fiel...
                                                                                 ^
mars 23 08:13:05 test3 python3.9[280204]: Odoo Server 14.0:test_odoo_preprod_14:ERROR:odoo.addons.base.models.ir_model:Failed to load field res.country.group.x_id_migrate: skipped
                                         Traceback (most recent call last):
                                           File "/home/preprod_odoo_14/server/odoo/addons/base/models/ir_model.py", line 1171, in _add_manual_fields
                                             field = self._instanciate(field_data)
                                           File "/home/preprod_odoo_14/server/odoo/addons/base/models/ir_model.py", line 1161, in _instanciate
                                             attrs = self._instanciate_attrs(field_data)
                                           File "/home/preprod_odoo_14/additionnal_repositories/OCA-pim/attribute_set/models/ir_model.py", line 17, in _instanciate_attrs
                                             self.env.cr.execute(
                                           File "<decorator-gen-3>", line 2, in execute
                                           File "/home/preprod_odoo_14/server/odoo/sql_db.py", line 101, in check
                                             return f(self, *args, **kwargs)
                                           File "/home/preprod_odoo_14/server/odoo/sql_db.py", line 301, in execute
                                             res = self._obj.execute(query, params)
                                         psycopg2.errors.UndefinedTable: ERREUR:  la relation « attribute_attribute » n'existe pas
                                         LIGNE 1 : SELECT company_dependent FROM attribute_attribute WHERE fiel...
                                                                                 ^
mars 23 08:13:05 test3 python3.9[280204]: Odoo Server 14.0:test_odoo_preprod_14:ERROR:odoo.sql_db:bad query: SELECT company_dependent FROM attribute_attribute WHERE field_id=17259
                                         ERROR: ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
                                         de la transaction

```

## To Reproduce
**Affected versions**:

14.0

1. just click on install

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by flotho** [comment]
maybe related to https://github.com/OCA/odoo-pim/issues/134 and https://github.com/OCA/odoo-pim/pull/135
